name: nextcloud
description: Nextcloud on Debian 13 (Trixie)
category: network
icon: nextcloud
version: 32.0.6
build_version: 3
base_os: debian-13
architecture: amd64
maintainer: mhzawadi <mhzawadi@users.noreply.github.com>
project_url: https://nextcloud.org

user:
  uid: 1101
  gid: 1100

resources:
  memory_min: 512
  memory_recommended: 1024
  disk_min: 10G
  disk_recommended: 16G
  cores: 1

ports:
  - port: 80
    description: HTTP

paths:
  - path: /var/lib/nextcloud
    description: nextcloud data

quick_start: |
  Web Server: http://<IP>
  Data: /var/lib/nextcloud

faq:
  - question: Where is my data?
    answer: |
      All the user data is stored in `/var/lib/nextcloud`
